// Copyright 2026 cr1m1 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Ad struct {
	CategoryId    int             `json:"category_id"`
	City          string          `json:"city"`
	CityAlias     string          `json:"city_alias"`
	CityId        int             `json:"city_id"`
	CountryId     int             `json:"country_id"`
	CreatedTime   int             `json:"created_time"`
	Currency      string          `json:"currency"`
	Description   string          `json:"description"`
	FavoriteCount int             `json:"favorite_count"`
	Id            int             `json:"id"`
	Images        json.RawMessage `json:"images"`
	Impressions   int             `json:"impressions"`
	IsNegotiable  bool            `json:"is_negotiable"`
	IsPremium     bool            `json:"is_premium"`
	IsSelect      bool            `json:"is_select"`
	IsVip         bool            `json:"is_vip"`
	Lat           float64         `json:"lat"`
	Lng           float64         `json:"lng"`
	Mobile        string          `json:"mobile"`
	Params        json.RawMessage `json:"params"`
	Price         float64         `json:"price"`
	StatusId      int             `json:"status_id"`
	Symbol        string          `json:"symbol"`
	Title         string          `json:"title"`
	UpdatedTime   int             `json:"updated_time"`
	User          json.RawMessage `json:"user"`
	UserId        int             `json:"user_id"`
	Views         int             `json:"views"`
}

type AdParam struct {
	Id      int    `json:"id"`
	Name    string `json:"name"`
	Value   string `json:"value"`
	ValueId int    `json:"value_id"`
}

type AdUser struct {
	Avatar       string `json:"avatar"`
	Id           int    `json:"id"`
	IsBanned     bool   `json:"is_banned"`
	Pro          bool   `json:"pro"`
	ResponseInfo string `json:"response_info"`
	ResponseRate int    `json:"response_rate"`
	ResponseTime int    `json:"response_time"`
	Username     string `json:"username"`
}

type AdsGetCountResponse struct {
	AdsCount string `json:"ads_count"`
	FeedId   int    `json:"feed-id"`
	FeedName string `json:"feed-name"`
}

type AdsListResponse struct {
	Items json.RawMessage `json:"items"`
}

type Category struct {
	Active    bool            `json:"active"`
	AdsCount  int             `json:"ads_count"`
	Children  json.RawMessage `json:"children"`
	Color     string          `json:"color"`
	FeedType  string          `json:"feed_type"`
	IconImage string          `json:"icon_image"`
	Id        int             `json:"id"`
	Image     string          `json:"image"`
	Name      string          `json:"name"`
	Order     int             `json:"order"`
	ParentId  int             `json:"parent_id"`
	Url       string          `json:"url"`
}

type CategoryParam struct {
	Alias         string          `json:"alias"`
	Id            int             `json:"id"`
	IsMultiSelect bool            `json:"is_multi_select"`
	IsRange       bool            `json:"is_range"`
	Kind          string          `json:"kind"`
	Name          string          `json:"name"`
	Values        json.RawMessage `json:"values"`
}

type Country struct {
	Code                string `json:"code"`
	DefaultCurrencyCode string `json:"default_currency_code"`
	DefaultLanguage     string `json:"default_language"`
	Domain              string `json:"domain"`
	Id                  int    `json:"id"`
	IsSupportPayment    bool   `json:"is_support_payment"`
	Name                string `json:"name"`
	PhoneMask           string `json:"phone_mask"`
	TimeZone            string `json:"time_zone"`
}

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Name    string `json:"name"`
	Status  int    `json:"status"`
}

type Image struct {
	Height           int    `json:"height"`
	Id               int    `json:"id"`
	IsMain           bool   `json:"is_main"`
	OriginalUrl      string `json:"original_url"`
	OriginalWebpUrl  string `json:"original_webp_url"`
	ThumbnailUrl     string `json:"thumbnail_url"`
	ThumbnailWebpUrl string `json:"thumbnail_webp_url"`
	Width            int    `json:"width"`
}

type User struct {
	About           string `json:"about"`
	Avatar          string `json:"avatar"`
	BusinessProfile bool   `json:"businessProfile"`
	CreateTime      int    `json:"create_time"`
	Id              int    `json:"id"`
	IsBanned        bool   `json:"is_banned"`
	IsDeleted       bool   `json:"is_deleted"`
	Pro             bool   `json:"pro"`
	ResponseInfo    string `json:"response_info"`
	ResponseRate    int    `json:"response_rate"`
	ResponseTime    int    `json:"response_time"`
	Username        string `json:"username"`
	Verify          string `json:"verify"`
}
