// Copyright 2026 cr1m1 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Command lalafo-pp-mcp serves the Lalafo printed CLI's commands as MCP tools
// over stdio. It constructs the server, registers every mirrored tool via
// internal/mcp.RegisterTools, and serves until stdin closes. version is
// overridable at build time via `-ldflags "-X main.version=..."` (see
// .goreleaser.yaml).
package main

import (
	"fmt"
	"os"

	"github.com/mark3labs/mcp-go/server"
	"lalafo-pp-cli/internal/mcp"
)

var version = "1.0.0"

func main() {
	s := server.NewMCPServer("lalafo", version)
	mcp.RegisterTools(s)
	if err := server.ServeStdio(s); err != nil {
		fmt.Fprintf(os.Stderr, "lalafo-pp-mcp: %v\n", err)
		os.Exit(1)
	}
}
