// Copyright 2026 cr1m1 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Command lalafo-pp-cli is the entrypoint for the Lalafo printed CLI. It defers
// all behavior to internal/cli: Execute() runs the Cobra tree in
// non-interactive mode and returns a typed error whose exit code ExitCode()
// resolves. Errors are already surfaced to stderr by Cobra, so main only maps
// the outcome to a process exit code.
package main

import (
	"os"

	"lalafo-pp-cli/internal/cli"
)

func main() {
	if err := cli.Execute(); err != nil {
		os.Exit(cli.ExitCode(err))
	}
}
