// Copyright 2026 cr1m1 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAdsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "ads",
		Short:       "List, get, and search ads",
		Hidden:      false,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAdsGetCmd(flags))
	cmd.AddCommand(newAdsGetCountCmd(flags))
	cmd.AddCommand(newAdsListCmd(flags))
	cmd.AddCommand(newAdsSearchCmd(flags))
	return cmd
}
