// Copyright 2026 cr1m1 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAdsSearchCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagPerPage int
	var flagPage string
	var flagCategoryId string
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "search",
		Short: "Search ads by keyword query with optional category filter.",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  lalafo-pp-cli ads search --q example-value",
		Annotations: map[string]string{"pp:endpoint": "ads.search", "pp:method": "GET", "pp:path": "/v3/ads/search", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("q") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "q")
			}
			path := "/v3/ads/search"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "ads", path, map[string]string{
				"q":           formatCLIParamValue(flagQ),
				"per-page":    formatCLIParamValue(flagPerPage),
				"page":        formatCLIParamValue(flagPage),
				"category_id": formatCLIParamValue(flagCategoryId),
			}, nil, flagAll, "page", "page", "", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				printProvenance(cmd, envelopeAwareItemCount(data), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagQ, "q", "", "Search query")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 20, "Per page")
	cmd.Flags().StringVar(&flagPage, "page", "1", "Page")
	cmd.Flags().StringVar(&flagCategoryId, "category-id", "", "Filter by category ID")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
