// Copyright 2026 cr1m1 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"testing"

	"lalafo-pp-cli/internal/store"
)

// TestWriteThroughCache_SkipsNonCacheableCount is the F7 regression: the scalar
// /v3/ads/count aggregate must not be routed through the ads auto-cache, where
// it would upsert an ID-less row and emit a spurious "no extractable ID field"
// warning. noCacheResourceType makes write-through a complete no-op (the store
// is never even opened), while a real ad detail still caches.
func TestWriteThroughCache_SkipsNonCacheableCount(t *testing.T) {
	dataDir := t.TempDir()
	t.Setenv("LALAFO_DATA_DIR", dataDir)
	ctx := context.Background()
	dbPath := defaultDBPath("lalafo-pp-cli")

	count := json.RawMessage(`{"ads_count":123456,"feed-name":"main","feed-id":7}`)
	writeThroughCache(ctx, noCacheResourceType, count)
	if _, err := os.Stat(dbPath); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("non-cacheable read must not open/create the store; stat(%s) err = %v", dbPath, err)
	}

	ad := json.RawMessage(`{"id":114491517,"title":"iPhone 13"}`)
	writeThroughCache(ctx, "ads", ad)

	db, err := store.OpenWithContext(ctx, dbPath)
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	defer db.Close()
	ads, err := db.List("ads", 0)
	if err != nil {
		t.Fatalf("list ads: %v", err)
	}
	if len(ads) != 1 {
		t.Fatalf("cached ads rows = %d, want 1 (the real ad only, not the count)", len(ads))
	}
}
