// Copyright 2026 cr1m1 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/csv"
	"encoding/json"
	"strings"
	"testing"
)

// adsListEnvelope mirrors the shape lalafo's /v3/ads collection endpoints
// return: a domain array under "items" alongside "_meta"/"_links" sidecars.
// The formatters must project the inner rows, not dump the wrapper object.
const adsListEnvelope = `{
  "items": [
    {"id": 114491517, "title": "iPhone 13", "price": 25000, "city": "Bishkek"},
    {"id": 114491600, "title": "Samsung S21", "price": 18000, "city": "Osh"}
  ],
  "_meta": {"total_count": 2, "per_page": 20},
  "_links": {"self": "/v3/ads"}
}`

// TestUnwrapListEnvelope covers the shared locator that CSV/plain/table
// rendering uses to reach the inner rows of a list-envelope response.
func TestUnwrapListEnvelope(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name     string
		input    string
		wantOK   bool
		wantLen  int
		firstID  float64
		hasFirst bool
	}{
		{
			name:     "ads items envelope with metadata siblings",
			input:    adsListEnvelope,
			wantOK:   true,
			wantLen:  2,
			firstID:  114491517,
			hasFirst: true,
		},
		{
			name:   "stripe-style data wrapper",
			input:  `{"object":"list","data":[{"id":1},{"id":2},{"id":3}]}`,
			wantOK: true, wantLen: 3,
		},
		{
			name:   "single detail object is not an envelope",
			input:  `{"id":114491517,"title":"iPhone 13","price":25000}`,
			wantOK: false,
		},
		{
			name:   "bare array is not an envelope object",
			input:  `[{"id":1},{"id":2}]`,
			wantOK: false,
		},
		{
			name:   "scalar count response is not an envelope",
			input:  `{"ads_count":123456,"feed-name":"main","feed-id":7}`,
			wantOK: false,
		},
		{
			// An ad detail carries nested object-arrays (images, params). It
			// must NOT be mistaken for a list envelope, or `ads get` would
			// render a table of the sub-array instead of the ad.
			name:   "detail object with nested arrays is not an envelope",
			input:  `{"id":114491517,"title":"iPhone","images":[{"id":9,"url":"u"}],"params":[{"name":"year","value":2020}]}`,
			wantOK: false,
		},
		{
			name:   "detail object with a single nested array is not an envelope",
			input:  `{"id":114491517,"title":"iPhone","images":[{"id":9,"url":"u"}]}`,
			wantOK: false,
		},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, ok := unwrapListEnvelope(json.RawMessage(tc.input))
			if ok != tc.wantOK {
				t.Fatalf("unwrapListEnvelope ok = %v, want %v (raw=%s)", ok, tc.wantOK, got)
			}
			if !ok {
				return
			}
			var rows []map[string]any
			if err := json.Unmarshal(got, &rows); err != nil {
				t.Fatalf("unwrapped payload is not an array: %v (raw=%s)", err, got)
			}
			if len(rows) != tc.wantLen {
				t.Errorf("row count = %d, want %d", len(rows), tc.wantLen)
			}
			if tc.hasFirst {
				if id, _ := rows[0]["id"].(float64); id != tc.firstID {
					t.Errorf("rows[0].id = %v, want %v", rows[0]["id"], tc.firstID)
				}
			}
		})
	}
}

// TestListItemsForTabularOutput pins the row-resolution used by printOutput's
// table branch: bare arrays and list envelopes both yield rows; single objects
// and empty collections fall back (false) so the caller keeps its raw path.
func TestListItemsForTabularOutput(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name    string
		input   string
		wantOK  bool
		wantLen int
	}{
		{"bare array", `[{"id":1},{"id":2}]`, true, 2},
		{"list envelope", adsListEnvelope, true, 2},
		{"single object", `{"id":1,"title":"x"}`, false, 0},
		{"empty envelope", `{"items":[],"_meta":{}}`, false, 0},
		{"empty bare array", `[]`, false, 0},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			items, ok := listItemsForTabularOutput(json.RawMessage(tc.input))
			if ok != tc.wantOK {
				t.Fatalf("ok = %v, want %v", ok, tc.wantOK)
			}
			if ok && len(items) != tc.wantLen {
				t.Errorf("len = %d, want %d", len(items), tc.wantLen)
			}
		})
	}
}

// TestEnvelopeAwareItemCount covers the provenance "N results" counter: list
// envelopes must report their inner row count, not 0 (the bug that put "0
// results" above a populated table once the table default landed).
func TestEnvelopeAwareItemCount(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		in   string
		want int
	}{
		{"list envelope", adsListEnvelope, 2},
		{"bare array", `[{"id":1},{"id":2},{"id":3}]`, 3},
		{"empty envelope", `{"items":[],"_meta":{}}`, 0},
		{"empty array", `[]`, 0},
		{"single object", `{"id":1}`, 0},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := envelopeAwareItemCount(json.RawMessage(tc.in)); got != tc.want {
				t.Errorf("envelopeAwareItemCount(%s) = %d, want %d", tc.in, got, tc.want)
			}
		})
	}
}

// TestDetailResponseItemCount covers the provenance counter for single-resource
// fetches (ads get / ads get-count): a non-empty detail object must report 1,
// not 0 (the R1 regression — a successful `ads get <id>` printed "0 results
// (live)" directly above the ad it just fetched, because the old inline count
// unmarshaled the object into a []json.RawMessage that always came back empty).
// Arrays and list envelopes still report their row count; JSON null, an empty
// object, and an empty collection report 0.
func TestDetailResponseItemCount(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		in   string
		want int
	}{
		{"single ad detail object", `{"id":114121330,"title":"iPhone 13","price":25000}`, 1},
		{"detail object with nested arrays", `{"id":1,"images":[{"id":9}],"params":[{"name":"year"}]}`, 1},
		{"scalar count aggregate", `{"ads_count":123456,"feed-name":"main","feed-id":7}`, 1},
		{"list envelope", adsListEnvelope, 2},
		{"bare array", `[{"id":1},{"id":2},{"id":3}]`, 3},
		{"empty object", `{}`, 0},
		{"json null", `null`, 0},
		{"empty array", `[]`, 0},
		{"empty envelope", `{"items":[],"_meta":{}}`, 0},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := detailResponseItemCount(json.RawMessage(tc.in)); got != tc.want {
				t.Errorf("detailResponseItemCount(%s) = %d, want %d", tc.in, got, tc.want)
			}
		})
	}
}

// TestPrintCSV_ListEnvelope is the F3 regression: `ads list --csv` must emit a
// real CSV of the inner rows, not a single-line dump of the wrapper object.
func TestPrintCSV_ListEnvelope(t *testing.T) {
	t.Parallel()
	var buf bytes.Buffer
	if err := printCSV(&buf, json.RawMessage(adsListEnvelope)); err != nil {
		t.Fatalf("printCSV: %v", err)
	}
	records, err := csv.NewReader(strings.NewReader(buf.String())).ReadAll()
	if err != nil {
		t.Fatalf("output is not valid CSV: %v\noutput:\n%s", err, buf.String())
	}
	// Header + 2 data rows.
	if len(records) != 3 {
		t.Fatalf("record count = %d, want 3 (header + 2 rows)\noutput:\n%s", len(records), buf.String())
	}
	wantHeader := []string{"city", "id", "price", "title"}
	if strings.Join(records[0], ",") != strings.Join(wantHeader, ",") {
		t.Errorf("header = %v, want %v", records[0], wantHeader)
	}
	// A wrapper dump would have surfaced "_meta"/"_links" as columns; a real
	// projection carries the ad titles as cell values.
	if !strings.Contains(buf.String(), "iPhone 13") || !strings.Contains(buf.String(), "Samsung S21") {
		t.Errorf("expected ad titles in CSV rows, got:\n%s", buf.String())
	}
	if strings.Contains(buf.String(), "_meta") || strings.Contains(buf.String(), "_links") {
		t.Errorf("wrapper keys leaked into CSV output:\n%s", buf.String())
	}
}

// TestPrintCSV_NestedCellJSONEncoded is the F5 regression: nested objects/arrays
// must serialize as JSON, never as Go's map[...] fmt form.
func TestPrintCSV_NestedCellJSONEncoded(t *testing.T) {
	t.Parallel()
	input := `[{"id":103261,"capital":{"id":1,"lat":42.87,"lng":74.6},"country_languages":[{"code":"ky"}]}]`
	var buf bytes.Buffer
	if err := printCSV(&buf, json.RawMessage(input)); err != nil {
		t.Fatalf("printCSV: %v", err)
	}
	out := buf.String()
	if strings.Contains(out, "map[") {
		t.Errorf("nested cell leaked Go map[...] form:\n%s", out)
	}
	records, err := csv.NewReader(strings.NewReader(out)).ReadAll()
	if err != nil {
		t.Fatalf("output is not valid CSV: %v\noutput:\n%s", err, out)
	}
	// Find the capital column value in the single data row and confirm it is
	// parseable JSON with the expected nested key.
	header, row := records[0], records[1]
	capital := ""
	for i, h := range header {
		if h == "capital" {
			capital = row[i]
		}
	}
	if capital == "" {
		t.Fatalf("no capital column found in %v", header)
	}
	var obj map[string]any
	if err := json.Unmarshal([]byte(capital), &obj); err != nil {
		t.Errorf("capital cell is not valid JSON: %v (cell=%q)", err, capital)
	}
}

// TestPrintPlain_ListEnvelope is the F3/F4 regression for the --plain path.
func TestPrintPlain_ListEnvelope(t *testing.T) {
	t.Parallel()
	var buf bytes.Buffer
	if err := printPlain(&buf, json.RawMessage(adsListEnvelope)); err != nil {
		t.Fatalf("printPlain: %v", err)
	}
	lines := strings.Split(strings.TrimRight(buf.String(), "\n"), "\n")
	if len(lines) != 3 {
		t.Fatalf("line count = %d, want 3 (header + 2 rows)\noutput:\n%s", len(lines), buf.String())
	}
	if lines[0] != strings.Join([]string{"city", "id", "price", "title"}, "\t") {
		t.Errorf("header = %q", lines[0])
	}
	if !strings.Contains(buf.String(), "iPhone 13") {
		t.Errorf("expected row content, got:\n%s", buf.String())
	}
}

// TestPrintPlain_NestedCellJSONEncoded is the F5 regression for --plain.
func TestPrintPlain_NestedCellJSONEncoded(t *testing.T) {
	t.Parallel()
	input := `[{"id":1,"capital":{"id":2,"name":"Bishkek"}}]`
	var buf bytes.Buffer
	if err := printPlain(&buf, json.RawMessage(input)); err != nil {
		t.Fatalf("printPlain: %v", err)
	}
	if strings.Contains(buf.String(), "map[") {
		t.Errorf("nested cell leaked Go map[...] form:\n%s", buf.String())
	}
	if !strings.Contains(buf.String(), `"name":"Bishkek"`) {
		t.Errorf("expected JSON-encoded nested cell, got:\n%s", buf.String())
	}
}

// TestCellScalarString covers the scalar/non-scalar rendering rules directly.
func TestCellScalarString(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		in   any
		want string
	}{
		{"nil", nil, ""},
		{"string", "hi", "hi"},
		{"bool true", true, "true"},
		{"bool false", false, "false"},
		{"float whole", float64(114491517), "114491517"},
		{"float frac", float64(42.87), "42.87"},
		{"nested map", map[string]any{"id": float64(1)}, `{"id":1}`},
		{"nested slice", []any{float64(1), float64(2)}, `[1,2]`},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := cellScalarString(tc.in); got != tc.want {
				t.Errorf("cellScalarString(%v) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}
