// Copyright 2026 cr1m1 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"strings"
	"testing"
)

// TestWhichIndex_IsSeeded guards against the regression the review found: the
// generator shipped an empty whichIndex, so `which` returned "no curated
// capability index" for every query and the advertised discovery command was
// 100% non-functional. The index must carry the hero capabilities.
func TestWhichIndex_IsSeeded(t *testing.T) {
	if len(whichIndex) == 0 {
		t.Fatal("whichIndex is empty; `which` would return the no-curated-index error for every query")
	}
	// The commands the SKILL.md Command Reference leads with must be present.
	wantLeaves := []string{"ads search", "ads list", "ads get", "categories", "countries", "params", "users"}
	have := map[string]bool{}
	for _, e := range whichIndex {
		have[e.Command] = true
	}
	for _, cmd := range wantLeaves {
		if !have[cmd] {
			t.Errorf("whichIndex missing hero capability %q", cmd)
		}
	}
}

// TestWhichIndex_ResolvesRealQueries exercises the ranker end-to-end against the
// production index for natural-language capability queries an agent would type.
func TestWhichIndex_ResolvesRealQueries(t *testing.T) {
	cases := []struct {
		query   string
		wantCmd string
	}{
		{"search ads", "ads search"},
		{"list latest ads", "ads list"},
		{"category tree", "categories"},
		{"filter parameters", "params"},
		{"user profile", "users"},
		{"sync local store", "sync"},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.query, func(t *testing.T) {
			got := rankWhich(whichIndex, tc.query, 3)
			if len(got) == 0 {
				t.Fatalf("query %q returned no matches against the seeded index", tc.query)
			}
			if got[0].Entry.Command != tc.wantCmd {
				top := make([]string, 0, len(got))
				for _, m := range got {
					top = append(top, m.Entry.Command)
				}
				t.Errorf("query %q top match = %q, want %q (ranked: %s)",
					tc.query, got[0].Entry.Command, tc.wantCmd, strings.Join(top, ", "))
			}
		})
	}
}
